#!/usr/bin/env ruby

def set_color(color, default = 0)
  case color.downcase.gsub("\n", '')
    when /\d/ : color
    when 'black' : '0'
    when 'red' : '1'
    when 'green': '2'
    when 'yellow' : '3'
    when 'blue' : '4'
    when 'magenta' : '5'
    when 'cyan' : '6'
    when 'white' : '7'
    else
      default
  end
end

automigrate = `git config rails.automigrate`.index('true')
migratable = `git diff HEAD^`.index("db/migrate")
fg_color = set_color(`git config rails.automigrateforegroundcolor`, 7)
bg_color = set_color(`git config rails.automigratebackgroundcolor`, 0)
blink = (`git config rails.automigrateblink`.index('true')) ? 5 : 0

if migratable
  if automigrate
    puts "\e[#{blink};1;3#{fg_color};4#{bg_color}mMigrating Database(s)... Please wait.\e[0m"
    `rake db:migrate && rake db:test:prepare`
    puts "\e[#{blink};1;3#{fg_color};4#{bg_color}mDone migrating database(s).\e[0m"
  else
    puts "\e[#{blink};1;3#{fg_color};4#{bg_color}mThere are pending migrations.\e[0m"
  end
end